name: Run tests

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        env:
          OS: '${{ matrix.os }}'
        run: yarn test:report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.os }}
          path: report-${{ matrix.os }}.html
